[package]
name = "rustaxion"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["codec"] }
futures-util = "0.3.30"
byteorder = "1.5.0"
enum-repr-derive = "0.2.0"
